"""Where a loaded Ollama model lives (src/gpu_placement.py).

Every fixture string here was captured on the reference box today — an RTX
4070 Ti (12 GB, GPU 0) next to an RTX 5060 Ti (16 GB, GPU 1), Ollama 0.33.2 on
Windows: `nvidia-smi --query-compute-apps` with its `[N/A]` used_memory, the
WDDM counter instance names, and a modelfile as `/api/show` returns it. The
Linux shape (a number in MiB per process per card) is covered next to it.
"""
from __future__ import annotations

import pytest

from src import gpu_placement as gp
from src import gpu_shared_memory as gsm

MIB = 1024 ** 2
GIB = 1024 ** 3

UUID0 = "GPU-5ab72dd9-1a45-c3af-5e12-ac7796b1def7"
UUID1 = "GPU-15d17fee-8c0c-4be3-be46-35fb3e32f2aa"
LUID0 = "0x00000000_0x01aec8b1"
LUID1 = "0x00000000_0x01b3ff4f"
RUNNER = r"C:\Users\luis\AppData\Local\Programs\Ollama\lib\ollama\llama-server.exe"
BLOB = r"D:\LocalAI\ollama-models\blobs\sha256-dec52a6a7a3fdd3e5e8b4c9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b"

# The usage route's rows (MiB), as nvidia-smi reported them with qwen3.5:9b
# resident on GPU 1.
GPUS = [
    {"index": 0, "name": "NVIDIA GeForce RTX 4070 Ti", "uuid": UUID0, "bus_id": "00000000:01:00.0", "mem_used": 1046},
    {"index": 1, "name": "NVIDIA GeForce RTX 5060 Ti", "uuid": UUID1, "bus_id": "00000000:10:00.0", "mem_used": 9263},
]

APPS_SINGLE_WIN = f"{UUID1}, 00000000:10:00.0, 15948, {RUNNER}, [N/A]\n"
APPS_SPLIT_WIN = (
    f"{UUID0}, 00000000:01:00.0, 15948, {RUNNER}, [N/A]\n"
    f"{UUID1}, 00000000:10:00.0, 15948, {RUNNER}, [N/A]\n"
)
APPS_SPLIT_LINUX = (
    f"{UUID0}, 00000000:01:00.0, 15948, /usr/local/lib/ollama/llama-server, 8704\n"
    f"{UUID1}, 00000000:10:00.0, 15948, /usr/local/lib/ollama/llama-server, 10445\n"
)

MODELFILE = (
    '# Modelfile generated by "ollama show"\n'
    "# To build a new Modelfile based on this, replace FROM with:\n"
    "# FROM qwen3.5:9b\n"
    "\n"
    f"FROM {BLOB}\n"
    'TEMPLATE """{{ .Prompt }}"""\n'
    "PARAMETER num_ctx 32768\n"
)

# WDDM: the runner under GPU 1's luid, a browser under GPU 0's.
PROC_ROWS_SINGLE = gsm.parse_process_counters(
    {"pid_15948_luid_0x00000000_0x01b3ff4f_phys_0": 706 * MIB},
    {"pid_15948_luid_0x00000000_0x01b3ff4f_phys_0": 8823 * MIB,
     "pid_2448_luid_0x00000000_0x01aec8b1_phys_0": 300 * MIB},
)
ADAPTERS = {LUID1: 9270 * MIB, LUID0: 1051 * MIB}

PS_SINGLE = [{"name": "qwen3.5:9b", "size": 8_100_000_000, "size_vram": 8_100_000_000, "digest": "dec52a6a"}]


# ── parsers ─────────────────────────────────────────────────────────────────

def test_compute_apps_windows_rows_have_no_bytes_but_name_the_card():
    rows = gp.parse_compute_apps(APPS_SINGLE_WIN)
    assert rows == [{"uuid": UUID1, "bus_id": "00000000:10:00.0", "pid": 15948,
                     "process": RUNNER, "used_bytes": None}]


def test_compute_apps_linux_rows_carry_bytes_and_a_split_model_appears_twice():
    rows = gp.parse_compute_apps(APPS_SPLIT_LINUX)
    assert [(r["uuid"], r["pid"], r["used_bytes"]) for r in rows] == [
        (UUID0, 15948, 8704 * MIB), (UUID1, 15948, 10445 * MIB)]


def test_compute_apps_skips_headers_and_keeps_commas_in_the_process_name():
    text = ("gpu_uuid, gpu_bus_id, pid, process_name, used_memory\n"
            f"{UUID0}, 00000000:01:00.0, 7, C:\\Program Files\\a, b\\x.exe, 12\n"
            "garbage\n")
    rows = gp.parse_compute_apps(text)
    assert len(rows) == 1
    assert rows[0]["process"] == "C:\\Program Files\\a, b\\x.exe" and rows[0]["used_bytes"] == 12 * MIB
    assert gp.parse_compute_apps("") == []


def test_modelfile_blob_skips_the_commented_from_line():
    assert gp.parse_modelfile_blob(MODELFILE) == BLOB
    assert gp.parse_modelfile_blob("# FROM qwen3.5:9b\n") is None
    assert gp.parse_modelfile_blob("") is None
    assert gp.parse_modelfile_blob('FROM "/models/blobs/sha256-abc"\n') == "/models/blobs/sha256-abc"


def test_blob_key_ignores_directory_slash_style_and_case():
    win = gp.blob_key(BLOB)
    assert win.startswith("sha256-dec52a6a")
    assert gp.blob_key("/usr/share/ollama/.ollama/models/blobs/SHA256-DEC52A6A7A3FDD3E5E8B4C9F8A7B6C5D4E3F2A1B0C9D8E7F6A5B4C3D2E1F0A9B") == win
    assert gp.blob_key("sha256:dec52a6a7a3fdd3e5e8b4c9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b") == win
    assert gp.blob_key(None) == "" and gp.blob_key("") == ""


def test_runner_blob_from_cmdline():
    argv = [RUNNER, "--model", BLOB, "--ctx-size", "32768", "--port", "54011"]
    assert gp.runner_blob_from_cmdline(argv) == BLOB
    assert gp.runner_blob_from_cmdline(["llama-server", f"--model={BLOB}"]) == BLOB
    assert gp.runner_blob_from_cmdline(["ollama", "serve"]) is None
    assert gp.runner_blob_from_cmdline(["x", "--model"]) is None


# ── luid → GPU index ────────────────────────────────────────────────────────

def test_luids_map_exactly_through_a_runner_on_one_card():
    apps = gp.parse_compute_apps(APPS_SINGLE_WIN)
    out = gp.map_luids(GPUS, apps, PROC_ROWS_SINGLE, {})
    assert out == {LUID1: 1}                       # pid 15948: one GPU, one luid


def test_the_other_card_is_matched_by_adapter_total_when_unambiguous():
    apps = gp.parse_compute_apps(APPS_SINGLE_WIN)
    out = gp.map_luids(GPUS, apps, PROC_ROWS_SINGLE, ADAPTERS)
    # 1051 MB of adapter memory against GPU 0's 1046 MiB memory.used
    assert out == {LUID1: 1, LUID0: 0}


def test_a_split_runner_gives_no_exact_witness_so_both_cards_go_by_total():
    apps = gp.parse_compute_apps(APPS_SPLIT_WIN)
    rows = gsm.parse_process_counters({}, {
        "pid_15948_luid_0x00000000_0x01b3ff4f_phys_0": 10445 * MIB,
        "pid_15948_luid_0x00000000_0x01aec8b1_phys_0": 8704 * MIB,
    })
    gpus = [dict(GPUS[0], mem_used=9750), dict(GPUS[1], mem_used=10886)]
    adapters = {LUID0: 9757 * MIB, LUID1: 10893 * MIB}
    assert gp.map_luids(gpus, apps, rows, adapters) == {LUID0: 0, LUID1: 1}


def test_ambiguous_totals_map_nothing():
    """Two cards holding almost the same amount: guessing would put a model
    on the wrong card, so neither is mapped."""
    gpus = [dict(GPUS[0], mem_used=8000), dict(GPUS[1], mem_used=8100)]
    adapters = {LUID0: 8050 * MIB, LUID1: 8060 * MIB}
    assert gp.map_luids(gpus, [], [], adapters) == {}


def test_an_adapter_nowhere_near_any_card_is_not_matched():
    """An iGPU's luid (200 MB) must not be pinned onto a discrete card."""
    gpus = [dict(GPUS[0], mem_used=1046), dict(GPUS[1], mem_used=9263)]
    adapters = {"0x00000000_0x0000edb2": 200 * MIB, LUID0: 1051 * MIB, LUID1: 9270 * MIB}
    assert gp.map_luids(gpus, [], [], adapters) == {LUID0: 0, LUID1: 1}
    assert gp.map_luids([GPUS[0]], [], [], {"0x00000000_0x0000edb2": 200 * MIB}) == {}


def test_map_luids_survives_cards_without_a_reading():
    assert gp.map_luids([{"index": 0, "uuid": UUID0}], [], [], ADAPTERS) == {}


# ── pid ↔ model ─────────────────────────────────────────────────────────────

def test_models_match_their_runner_by_blob():
    models = [{"name": "qwen3.5:9b", "size_vram": 8 * GIB}, {"name": "gemma3:4b", "size_vram": 3 * GIB}]
    pid_blobs = {15948: BLOB, 16001: r"D:\LocalAI\ollama-models\blobs\sha256-aaaa"}
    model_blobs = {"qwen3.5:9b": BLOB, "gemma3:4b": "/x/blobs/sha256-aaaa"}
    assert gp.match_models_to_pids(models, pid_blobs, model_blobs, [15948, 16001], {}) == \
        {"qwen3.5:9b": 15948, "gemma3:4b": 16001}


def test_one_model_and_one_runner_need_no_blob():
    models = [{"name": "qwen3.5:9b", "size_vram": 8 * GIB}]
    assert gp.match_models_to_pids(models, {}, {}, [15948], {}) == {"qwen3.5:9b": 15948}
    # a CPU-only model is not a runner on a card
    assert gp.match_models_to_pids([{"name": "cpu:1", "size_vram": 0}], {}, {}, [15948], {}) == {}


def test_size_is_the_fallback_when_blobs_do_not_line_up():
    models = [{"name": "big:27b", "size_vram": 17 * GIB}, {"name": "small:9b", "size_vram": 8 * GIB}]
    pid_bytes = {1: 8_900_000_000, 2: 18_000_000_000}
    assert gp.match_models_to_pids(models, {}, {}, [1, 2], pid_bytes) == {"big:27b": 2, "small:9b": 1}
    # nothing measured: no guess
    assert gp.match_models_to_pids(models, {}, {}, [1, 2], {}) == {}


# ── the answer per model ────────────────────────────────────────────────────

def test_describe_single_split_cpu_and_unknown():
    models = [
        {"name": "one", "size_vram": 8 * GIB},
        {"name": "two", "size_vram": 17 * GIB},
        {"name": "cpu", "size_vram": 0},
        {"name": "lost", "size_vram": 5 * GIB},
    ]
    assigned = {"one": 15948, "two": 16001, "cpu": 16002}
    pid_gpus = {15948: {1: 8823 * MIB}, 16001: {0: 8704 * MIB, 1: 10445 * MIB}, 16002: {0: 300 * MIB}}
    out = gp.describe(models, assigned, pid_gpus, GPUS)
    assert out["one"] == {"gpus": [1], "per_gpu": [{"index": 1, "bytes": 8823 * MIB}], "placement": "single", "pid": 15948}
    assert out["two"]["placement"] == "split" and out["two"]["gpus"] == [0, 1]
    assert out["two"]["per_gpu"] == [{"index": 0, "bytes": 8704 * MIB}, {"index": 1, "bytes": 10445 * MIB}]
    assert out["cpu"] == {"gpus": [], "per_gpu": [], "placement": "cpu", "pid": 16002}
    assert out["lost"] == {"gpus": [], "per_gpu": [], "placement": "unknown", "pid": None}


def test_a_whole_model_on_one_card_takes_its_bytes_from_ollama_ps():
    """Windows without a luid mapping: nvidia-smi names the card but not the
    bytes — `ollama ps` already measured the model, and it is all there."""
    out = gp.describe([{"name": "one", "size_vram": 8 * GIB}], {"one": 1}, {1: {1: None}}, GPUS)
    assert out["one"]["per_gpu"] == [{"index": 1, "bytes": 8 * GIB}] and out["one"]["placement"] == "single"


def test_one_card_in_the_box_is_where_a_resident_model_lives():
    out = gp.describe([{"name": "one", "size_vram": 8 * GIB}], {}, {}, [GPUS[0]])
    assert out["one"] == {"gpus": [0], "per_gpu": [{"index": 0, "bytes": 8 * GIB}], "placement": "single", "pid": None}
    # …but not when there are two: that would be a guess
    assert gp.describe([{"name": "one", "size_vram": 8 * GIB}], {}, {}, GPUS)["one"]["placement"] == "unknown"


def test_per_gpu_turns_it_around_and_lists_every_card():
    models = {
        "one": {"gpus": [1], "per_gpu": [{"index": 1, "bytes": 8823 * MIB}], "placement": "single", "pid": 15948},
        "two": {"gpus": [0, 1], "per_gpu": [{"index": 0, "bytes": None}, {"index": 1, "bytes": 10 * GIB}], "placement": "split", "pid": 16001},
    }
    out = gp.per_gpu(models, {15948: {1: None}, 16001: {0: None, 1: None}, 777: {0: None}}, [15948, 16001, 777], GPUS)
    assert out[0] == {"models": [{"name": "two", "bytes": None}], "runner_pids": [777, 16001]}
    assert out[1] == {"models": [{"name": "one", "bytes": 8823 * MIB}, {"name": "two", "bytes": 10 * GIB}],
                      "runner_pids": [15948, 16001]}
    assert gp.per_gpu({}, {}, [], GPUS) == {0: {"models": [], "runner_pids": []}, 1: {"models": [], "runner_pids": []}}


# ── end to end, collectors faked ────────────────────────────────────────────

@pytest.fixture
def box(monkeypatch):
    """The reference box: collectors return the captured strings."""
    state = {"apps": APPS_SINGLE_WIN, "procs": {15948: "llama-server.exe", 4000: "ollama.exe"},
             "blobs": {15948: BLOB}, "show": {"qwen3.5:9b": MODELFILE},
             "wddm": {"processes": PROC_ROWS_SINGLE, "adapters": ADAPTERS}, "calls": []}

    def _apps():
        state["calls"].append("nvidia-smi")
        return gp.parse_compute_apps(state["apps"])

    def _show(base, name, digest=""):
        state["calls"].append(("show", name))
        text = state["show"].get(name)
        return gp.parse_modelfile_blob(text) if text else None

    monkeypatch.setattr(gp, "_compute_apps", _apps)
    monkeypatch.setattr(gsm, "runner_pids", lambda: dict(state["procs"]))
    monkeypatch.setattr(gp, "_runner_blobs", lambda pids: {p: b for p, b in state["blobs"].items() if p in pids})
    monkeypatch.setattr(gp, "_show_blob", _show)
    monkeypatch.setattr(gp, "_wddm", lambda: state["wddm"])
    gp.reset_cache()
    yield state
    gp.reset_cache()


def test_single_model_on_the_freest_card(box):
    out = gp.placement("http://127.0.0.1:11434", PS_SINGLE, GPUS)
    assert out == {"qwen3.5:9b": {"gpus": [1], "per_gpu": [{"index": 1, "bytes": 8823 * MIB}],
                                  "placement": "single", "pid": 15948}}
    per = gp.gpus_runners("http://127.0.0.1:11434", PS_SINGLE, GPUS)
    assert per[1] == {"models": [{"name": "qwen3.5:9b", "bytes": 8823 * MIB}], "runner_pids": [15948]}
    assert per[0] == {"models": [], "runner_pids": []}
    assert ("show", "qwen3.5:9b") in box["calls"]


def test_split_model_on_windows_takes_per_card_bytes_from_the_counters(box):
    box["apps"] = APPS_SPLIT_WIN
    box["wddm"] = {
        "processes": gsm.parse_process_counters({}, {
            "pid_15948_luid_0x00000000_0x01b3ff4f_phys_0": 10445 * MIB,
            "pid_15948_luid_0x00000000_0x01aec8b1_phys_0": 8704 * MIB,
        }),
        "adapters": {LUID0: 9757 * MIB, LUID1: 10893 * MIB},
    }
    gpus = [dict(GPUS[0], mem_used=9750), dict(GPUS[1], mem_used=10886)]
    ps = [{"name": "qwen3.8:27b-q4_K_M", "size": 17_000_000_000, "size_vram": 17_000_000_000}]
    box["show"] = {"qwen3.8:27b-q4_K_M": MODELFILE}
    out = gp.placement("http://127.0.0.1:11434", ps, gpus)["qwen3.8:27b-q4_K_M"]
    assert out["placement"] == "split" and out["gpus"] == [0, 1]
    assert out["per_gpu"] == [{"index": 0, "bytes": 8704 * MIB}, {"index": 1, "bytes": 10445 * MIB}]


def test_split_model_on_linux_takes_per_card_bytes_from_nvidia_smi(box):
    box["apps"] = APPS_SPLIT_LINUX
    box["wddm"] = None
    box["blobs"] = {15948: "/usr/share/ollama/.ollama/models/blobs/sha256-dec52a6a7a3fdd3e5e8b4c9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b"}
    ps = [{"name": "qwen3.8:27b-q4_K_M", "size": 17_000_000_000, "size_vram": 17_000_000_000}]
    box["show"] = {"qwen3.8:27b-q4_K_M": MODELFILE}
    out = gp.placement("http://127.0.0.1:11434", ps, gpus=GPUS)["qwen3.8:27b-q4_K_M"]
    assert out["placement"] == "split"
    assert out["per_gpu"] == [{"index": 0, "bytes": 8704 * MIB}, {"index": 1, "bytes": 10445 * MIB}]
    assert gp.gpus_runners("http://127.0.0.1:11434", ps, GPUS)[0]["runner_pids"] == [15948]


def test_a_cpu_only_model_says_cpu(box):
    ps = [{"name": "huge:70b", "size": 40 * GIB, "size_vram": 0}]
    out = gp.placement("http://127.0.0.1:11434", ps, GPUS)["huge:70b"]
    assert out["placement"] == "cpu" and out["gpus"] == [] and out["per_gpu"] == []


def test_nothing_loaded_means_nothing_run_and_nothing_fetched(box):
    assert gp.placement("http://127.0.0.1:11434", [], GPUS) == {}
    assert gp.gpus_runners("http://127.0.0.1:11434", [], GPUS) == {0: {"models": [], "runner_pids": []},
                                                                   1: {"models": [], "runner_pids": []}}
    assert box["calls"] == []


def test_no_show_call_without_a_runner_to_match_against(box):
    box["blobs"] = {}
    box["procs"] = {}
    box["apps"] = ""
    out = gp.placement("http://127.0.0.1:11434", PS_SINGLE, GPUS)
    assert out["qwen3.5:9b"]["placement"] == "unknown"
    assert not any(isinstance(c, tuple) and c[0] == "show" for c in box["calls"])


def test_the_answer_is_cached_for_a_couple_of_seconds(box):
    gp.placement("http://127.0.0.1:11434", PS_SINGLE, GPUS)
    n = box["calls"].count("nvidia-smi")
    gp.placement("http://127.0.0.1:11434", PS_SINGLE, GPUS)
    assert box["calls"].count("nvidia-smi") == n
    # a different set of loaded models is a different question
    gp.placement("http://127.0.0.1:11434", PS_SINGLE + [{"name": "x:1", "size_vram": 1}], GPUS)
    assert box["calls"].count("nvidia-smi") == n + 1


def test_placement_never_raises(box, monkeypatch):
    def _boom():
        raise RuntimeError("nvidia-smi exploded")

    monkeypatch.setattr(gp, "_compute_apps", _boom)
    assert gp.placement("http://127.0.0.1:11434", PS_SINGLE, GPUS) == {}
    assert gp.gpus_runners("http://127.0.0.1:11434", PS_SINGLE, GPUS) == {0: {"models": [], "runner_pids": []},
                                                                          1: {"models": [], "runner_pids": []}}


def test_without_a_gpu_list_the_snapshot_is_asked(box, monkeypatch):
    monkeypatch.setattr(gsm, "vram_snapshot", lambda: {
        "supported": True, "count": 2, "gpus": [
            {"index": 0, "name": "a", "uuid": UUID0, "total": 12 * GIB, "used": 1046 * MIB, "free": 1},
            {"index": 1, "name": "b", "uuid": UUID1, "total": 16 * GIB, "used": 9263 * MIB, "free": 1},
        ]})
    out = gp.placement("http://127.0.0.1:11434", PS_SINGLE)
    assert out["qwen3.5:9b"]["gpus"] == [1] and out["qwen3.5:9b"]["per_gpu"][0]["bytes"] == 8823 * MIB


def test_wddm_is_windows_only_and_quiet_elsewhere(monkeypatch):
    monkeypatch.setattr(gp.sys, "platform", "linux")
    assert gp._wddm() is None
