import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
const dir = mkdtempSync(join(tmpdir(), 'faustus-pages-'));
const out = join(dir, 'cursor.mjs');
await build({entryPoints:['studio/src/lib/page-cursor.ts'], bundle:true, platform:'node', format:'esm', outfile:out});
const {PageCursor} = await import(pathToFileURL(out));
const cursor = new PageCursor();
const first = cursor.begin(false);
assert.equal(first.offset, 0);
cursor.accept(first, Array.from({length:48}, (_,i)=>({id:String(i)})));
const next = cursor.begin(true);
assert.equal(next.offset, 48, 'show more must never reuse an initial render offset');
assert.equal(cursor.begin(true), null, 'double-click cannot request the same page twice');
const newer = cursor.begin(false);
assert.ok(next.signal.aborted);
assert.equal(cursor.accept(next, [{id:'old-filter'}]), null);
assert.equal(cursor.fail(next), false, 'late failure cannot clear a new request');
cursor.accept(newer, [{id:'new-filter'}]);
const overlap = cursor.begin(true);
cursor.accept(overlap, [{id:'new-filter'}, {id:'second'}]);
assert.deepEqual(cursor.rows.map(r=>r.id), ['new-filter', 'second']);
assert.equal(cursor.offset, 3, 'offset counts server rows, not deduplicated display rows');
const cancelled = cursor.begin(true);
cursor.cancel();
assert.equal(cursor.accept(cancelled, [{id:'after-unmount'}]), null);
console.log('Page cursor: pagination, duplicate clicks, late responses, cancellation and overlapping pages pass.');
