import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle = await build({entryPoints:['studio/src/adapters/projects.ts'],bundle:true,format:'esm',platform:'node',write:false});
const p = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const link = (id, extra={}) => p.contextLinkFrom({id,kind:'file',path:'/notes.md',...extra});
assert.equal(link('a').accessMode,'read_only');
assert.equal(link('a',{access_mode:'full-access'}).accessMode,'read_only');
assert.equal(link('a',{retrieval_policy:'unknown'}).retrievalPolicy,'on_demand');
assert.equal(link('a',{pinned_version:1.5}).pinnedVersion,null);
assert.equal(link('a',{pinned_version:3}).pinnedVersion,3);
assert.equal(link('a',{source_checked_at:Infinity}).sourceCheckedAt,0);
assert.equal(link('a',{source_checked_at:10,source_state:'invalid'}).sourceState,'unsupported');
assert.equal(p.persistedLinkStatus(link('a')),undefined);
assert.equal(p.linkIsBroken(),false);
assert.equal(p.linkIsBroken({state:'forbidden'}),true);
assert.equal(p.linkIsBehind(link('a',{index_status:'stale'})),true);
assert.equal(p.linkIsBehind(link('a'),{state:'ok',stale:true}),true);
assert.equal(p.linkIsBehind(link('a'),{state:'missing',stale:true}),false);
const links=[link('r',{role:'archive'}),link('z',{role:'z_custom'}),link('a',{role:'a_custom'}),link('q',{role:'requirements'})];
assert.deepEqual(p.groupLinksByRole(links).map(g=>g.role),['requirements','archive','a_custom','z_custom']);
assert.deepEqual(links.map(l=>l.id),['r','z','a','q']);
const counts=p.countLinks([
  link('1',{access_mode:'work_root'}),link('2',{index_status:'stale'}),
  link('3',{source_state:'missing',source_checked_at:1}),link('4',{enabled:false}),
  link('5',{retrieval_policy:'disabled'})],{});
assert.deepEqual(counts,{total:5,editable:1,behind:1,broken:1,off:2});
assert.equal(p.countLinks([link('3',{source_state:'missing',source_checked_at:1})],{'3':{state:'ok'}}).broken,0);
assert.deepEqual(p.parseDeps('OBJ-1, 2 obj-3;2 junk --4'),['OBJ-1','OBJ-2','OBJ-3']);
assert.equal(p.refusalOf({ok:true}),null);
assert.equal(p.refusalOf({ok:false}).message,'refused');
assert.equal(p.refusalOf({ok:false,error:{message:'not allowed'}}).message,'not allowed');
assert.deepEqual(p.groupLinksByRole([]),[]);
const objectives=[{id:'OBJ-2',status:'open',priority:2},{id:'OBJ-3',status:'done',priority:1},{id:'OBJ-10',status:'blocked',priority:1}];
assert.deepEqual(p.sortObjectives(objectives).map(o=>o.id),['OBJ-10','OBJ-2','OBJ-3']);
assert.equal(objectives[0].id,'OBJ-2');
let call;
globalThis.fetch=async(url,init)=>{call={url,init};return Response.json({ok:true,link:{id:'saved',kind:'document'}});};
await p.attachContextSource('a/b',{kind:'document',id:'doc1'});
assert.equal(call.url,'/api/projects/a%2Fb/context');
assert.equal(call.init.credentials,'same-origin');
assert.equal(JSON.parse(call.init.body).access_mode,'read_only');
globalThis.fetch=async()=>Response.json({ok:false,error:{message:'permission refused'}});
await assert.rejects(p.attachContextSource('a',{kind:'file'}),/permission refused/);
await assert.rejects(p.listContextLinks('a'),/permission refused/);
globalThis.fetch=async()=>Response.json({ok:true});
await assert.rejects(p.attachContextSource('a',{kind:'file'}),e=>e.status===502);
globalThis.fetch=async()=>Response.json({state:'future-unknown-state'});
await assert.rejects(p.inspectContextLink('a','b'),e=>e.status===502);
console.log('ALL OK: project permissions, counts, parsing, refusal and transport contracts');
