import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle = await build({entryPoints:['studio/src/adapters/settings.ts'],bundle:true,format:'esm',platform:'node',write:false});
const settings = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
let calls=[];
globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json([{id:'one'},{id:'two'},{id:'one'},{id:null},'three']);};
assert.deepEqual(await settings.refreshEndpointModels('a/b'),['one','two','three']);
assert.match(calls[0].url,/a%2Fb/);
globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({online:true,models:[{id:'one'},'two',null]});};
const signal=new AbortController().signal;
assert.deepEqual((await settings.testEndpoint('https://api.openai.com/v1','dummy-test',signal)).models,['one','two']);
assert.equal((await settings.testEndpoint('https://api.openai.com/v1','dummy-test',signal)).privateConnectionsSupported,false);
assert.equal(calls.at(-1).init.signal,signal);
await settings.addEndpoint({name:'OpenAI',baseUrl:'https://api.openai.com/v1',apiKey:'dummy-test',modelType:'llm',kind:'api',pinnedModels:['one'],shared:false,requireModels:true},signal);
const body=calls.at(-1).init.body;
assert.equal(body.get('shared'),'false');assert.equal(body.get('require_models'),'true');
assert.equal(body.get('pinned_models'),'["one"]');assert.equal(body.get('endpoint_kind'),'api');
assert.equal(calls.at(-1).init.signal,signal);
globalThis.fetch=async()=>Response.json({detail:'denied'},{status:403});
assert.equal((await settings.testEndpoint('https://example.test','dummy')).ok,false);
console.log('ALL OK: provider adapter contracts');
