import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle = await build({entryPoints:['studio/src/adapters/runner-connections.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {parseRunnerConnection,checkRunnerConnection} = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const payload = (patch={}) => ({connection:{runner:'codex',state:'connected',auth_method:'subscription',installed:true,authenticated:true,external_runners_enabled:false,...patch}});
assert.equal(parseRunnerConnection(payload(),'codex').authMethod,'subscription');
assert.equal(parseRunnerConnection(payload(),'codex').enabled,false);
for(const patch of [{authenticated:'true'},{installed:'true'},{auth_method:['api']},{auth_method:'future'}, {state:'unexpected'}]) assert.equal(parseRunnerConnection(payload(patch),'codex').state,'unverified');
assert.throws(()=>parseRunnerConnection(payload(),'claude'));
for(const raw of [null,[],{}, {connection:null}]) assert.throws(()=>parseRunnerConnection(raw,'codex'));
assert.deepEqual(parseRunnerConnection(payload({environment_override_names:['OPENAI_API_KEY','sk-secret','secret=value',null]}),'codex').overrides,['OPENAI_API_KEY']);
const signal=new AbortController().signal;
let call;
globalThis.fetch=async(url,init)=>{call={url,init};return Response.json(payload());};
assert.equal((await checkRunnerConnection('codex',signal)).state,'connected');
assert.equal(call.url,'/api/agent-runners/codex/connection');
assert.equal(call.init.signal,signal);
assert.equal(call.init.credentials,'same-origin');
globalThis.fetch=async()=>Response.json({detail:'secret'},{status:403});
await assert.rejects(checkRunnerConnection('claude',signal),error=>error.status===403&&!error.message.includes('secret'));
console.log('ALL OK: official client connection contracts');
