import assert from 'node:assert/strict';
import {build} from 'esbuild';
const bundle = await build({entryPoints:['studio/src/adapters/ssh-trust.ts'],bundle:true,format:'esm',platform:'node',write:false});
const {parseSshTrust,sshTrustAction} = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const fingerprint = 'SHA256:'+'a'.repeat(43);
const payload = {host:'[gpu-box]:2222',state:'unpaired',paired:[],offered:[{type:'ssh-ed25519',fingerprint}]};
assert.equal(parseSshTrust(payload).state,'unpaired');
for (const raw of [null,{}, {...payload,state:'unknown'}, {...payload,offered:[]}, {...payload,offered:[{type:'key',fingerprint:'invalid'}]}]) assert.throws(()=>parseSshTrust(raw));
let call;
globalThis.fetch = async (url,init) => {call={url,init}; return Response.json(payload);};
const signal=new AbortController().signal;
await sshTrustAction('fingerprint','alice@gpu-box','2222',signal);
assert.equal(call.url,'/api/cookbook/ssh/fingerprint');
assert.deepEqual(JSON.parse(call.init.body),{host:'alice@gpu-box',ssh_port:'2222'});
assert.equal(call.init.credentials,'same-origin');
assert.equal(call.init.signal,signal);
await sshTrustAction('pair','alice@gpu-box','2222',signal,fingerprint);
assert.equal(JSON.parse(call.init.body).fingerprint,fingerprint);
globalThis.fetch = async () => Response.json({detail:'private diagnostic'}, {status:409});
await assert.rejects(sshTrustAction('pair','host',undefined,signal,fingerprint),e=>e.status===409&&!e.message.includes('private'));
console.log('ALL OK: SSH trust contracts');
