import assert from 'node:assert/strict';
import { build } from 'esbuild';
const result = await build({ entryPoints: ['studio/src/voice/engine.ts'], bundle: true, format: 'esm', platform: 'node', write: false });
const { SentenceBuffer, TurnDetector, spokenText, speechLanguage } = await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
assert.equal(speechLanguage('Here is the answer you requested.', 'es'), 'en');
assert.equal(speechLanguage('Aquí tienes una respuesta para tu proyecto.', 'en'), 'es');
assert.equal(speechLanguage('Hello.', 'es'), 'en');
assert.equal(speechLanguage('Hola.', 'en'), 'es');
assert.equal(speechLanguage('42.', 'es'), 'es');
const s = new SentenceBuffer();
assert.deepEqual(s.take('Hola'), []);
assert.deepEqual(s.take('Hola. Estoy'), ['Hola.']);
assert.deepEqual(s.take('Hola. Estoy trabajando. Ya'), ['Estoy trabajando.']);
assert.deepEqual(s.take('Hola. Estoy trabajando. Ya terminé.', true), ['Ya terminé.']);
assert.deepEqual(s.take('Hola. Estoy trabajando. Ya terminé.', true), []);
assert.equal(spokenText('Texto. ```python\nprint("secret")'), 'Texto.');
assert.equal(spokenText('Texto. ```py\nx\n``` Final.'), 'Texto. Final.');
assert.equal(spokenText('[Referencia](https://example.com) **buena**'), 'Referencia buena');
assert.equal(spokenText('| precio | total |\n| 12 | 30 |\nResultado.'), 'Resultado.');
assert.deepEqual(new SentenceBuffer().take('Cuesta 12.50 euros. Siguiente'), ['Cuesta 12.50 euros.']);
assert.deepEqual(new SentenceBuffer().take('El Dr. López viene. Siguiente'), ['El Dr. López viene.']);
const budget = new SentenceBuffer(6);
assert.deepEqual(budget.take('Hola. Más cosas.', true), ['Hola.']);
assert.equal(budget.truncated, true);
const detector = new TurnDetector();
for (let now = 50; now < 1000; now += 50) assert.equal(detector.push(0, now), 'continue');
for (let now = 1000; now <= 1400; now += 50) detector.push(0.1, now);
assert.equal(detector.push(0, 2000), 'continue');
assert.equal(detector.push(0, 2700), 'silence');
const quiet = new TurnDetector(); quiet.push(0, 100);
assert.equal(quiet.push(0, 15200), 'empty');
const long = new TurnDetector(); long.push(0.1, 100);
assert.equal(long.push(0.1, 60100), 'limit');
console.log('ALL OK: voice segmentation, bounded output, silence, duration, decimals, code and links');
