"""S1.3: export the real app's OpenAPI document to a file, offline.

    python scripts/export_openapi.py [--out build/openapi.json]

The point is the same as the other `scripts/*_openapi_check.py` files in
this repo: `import app` and read what FastAPI actually built from the
mounted routers, not a hand-maintained copy of the surface. Unlike those
(read-only checks against the developer's own already-initialised `data/`),
this one is meant to run in a clean checkout or CI, so it points
`FAUSTUS_DATA_DIR`/`DATABASE_URL` at a throwaway temp location BEFORE
importing `app` — `core/database.py` creates its data dir and opens its
database as an import-time side effect, and the real `data/` (or whatever a
caller already exported) must never be that side effect. Both are set with
`setdefault`, so an operator who already exported a real `DATABASE_URL`
(a CI Postgres, say) keeps it.

The output is NOT committed (`build/` is gitignored) — it is meant to be
regenerated by whoever needs it (S2's TypeScript client, most immediately),
the same reason a lockfile is generated, not written by hand.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))


def _prepare_isolated_environment() -> None:
    """Point the app's data dir and database at a throwaway temp location
    before `import app` runs its module-level init. `setdefault` so a
    caller's own `FAUSTUS_DATA_DIR`/`DATABASE_URL` (a real CI database, an
    already-exported location) is never overridden."""
    os.environ.setdefault("FAUSTUS_DATA_DIR", tempfile.mkdtemp(prefix="faustus-openapi-export-"))
    os.environ.setdefault("DATABASE_URL", "sqlite:///:memory:")
    # Matches the test suite's own defaults (tests/conftest.py) for a clean,
    # network-free import: no real Chroma/MCP process needed just to read
    # the OpenAPI document off the mounted routers.
    os.environ.setdefault("CHROMADB_CONNECT_TIMEOUT", "0.01")
    os.environ.setdefault("FAUSTUS_DISABLE_MCP", "1")
    os.environ.setdefault("AUTH_ENABLED", "true")


def export_openapi(out_path: Path) -> dict:
    _prepare_isolated_environment()
    import app as application  # noqa: PLC0415 - the import IS the point

    spec = application.app.openapi()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as handle:
        json.dump(spec, handle, indent=2, sort_keys=True)
        handle.write("\n")
    return spec


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", default=str(REPO_ROOT / "build" / "openapi.json"),
        help="Where to write the OpenAPI document (default: build/openapi.json)",
    )
    args = parser.parse_args()
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = REPO_ROOT / out_path

    spec = export_openapi(out_path)

    api_version = spec.get("info", {}).get("x-api-version")
    path_count = len(spec.get("paths", {}))
    print(f"wrote {out_path} — {path_count} paths, x-api-version={api_version!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
