/**
 * `:shortcode:` → Unicode emoji, ported from the previous interface's
 * `emojiShortcodes.js` (issue #345) with the table kept verbatim.
 *
 * Chat models routinely write `:blush:`, `:fire:`, `:microphone:` instead of
 * the character. Nothing downstream translated them, so they reached the
 * bubble as literal text. This is the only place that translation happens, and
 * it runs on the raw text before Markdown, so a shortcode inside a fenced code
 * block is left alone by the caller, not by this module.
 */

const TABLE: Record<string, string> = {
  // ── Smileys & emotion ──
  grinning: '😀', grinning_face: '😀',
  smiley: '😃', smiley_face: '😃',
  smile: '😄',
  grin: '😁',
  laughing: '😆', satisfied: '😆',
  sweat_smile: '😅',
  rofl: '🤣', rolling_on_the_floor_laughing: '🤣',
  joy: '😂',
  slightly_smiling_face: '🙂', slight_smile: '🙂',
  upside_down_face: '🙃', upside_down: '🙃',
  wink: '😉', winking_face: '😉',
  blush: '😊', smiling_face_with_smiling_eyes: '😊',
  innocent: '😇',
  smiling_face_with_three_hearts: '🥰',
  heart_eyes: '😍', heart_eyes_face: '😍',
  star_struck: '🤩',
  kissing_heart: '😘',
  kissing: '😗',
  kissing_closed_eyes: '😚',
  kissing_smiling_eyes: '😙',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  zany_face: '🤪',
  stuck_out_tongue_closed_eyes: '😝',
  money_mouth_face: '🤑',
  hugs: '🤗', hugging_face: '🤗',
  hand_over_mouth: '🤭',
  shushing_face: '🤫',
  thinking: '🤔', thinking_face: '🤔',
  zipper_mouth_face: '🤐',
  raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smirk: '😏', smirk_face: '😏',
  unamused: '😒',
  roll_eyes: '🙄', face_with_rolling_eyes: '🙄',
  grimacing: '😬',
  lying_face: '🤥',
  relieved: '😌',
  pensive: '😔',
  sleepy: '😪',
  drooling_face: '🤤',
  sleeping: '😴',
  mask: '😷',
  face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕',
  nauseated_face: '🤢',
  vomiting_face: '🤮',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  dizzy_face: '😵',
  exploding_head: '🤯',
  cowboy_hat_face: '🤠',
  partying_face: '🥳',
  sunglasses: '😎',
  nerd_face: '🤓',
  monocle_face: '🧐',
  confused: '😕',
  worried: '😟',
  slightly_frowning_face: '🙁',
  frowning_face: '☹️',
  open_mouth: '😮',
  hushed: '😯',
  astonished: '😲',
  flushed: '😳',
  pleading_face: '🥺',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  cold_sweat: '😰',
  disappointed_relieved: '😥',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  confounded: '😖',
  persevere: '😣',
  disappointed: '😞',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  yawning_face: '🥱',
  triumph: '😤',
  rage: '😡', pout: '😡', pouting_face: '😡',
  angry: '😠',
  cursing_face: '🤬',
  smiling_imp: '😈',
  imp: '👿',
  skull: '💀',
  skull_and_crossbones: '☠️',
  hankey: '💩', poop: '💩', shit: '💩',
  clown_face: '🤡',
  japanese_ogre: '👹',
  japanese_goblin: '👺',
  ghost: '👻',
  alien: '👽',
  space_invader: '👾',
  robot: '🤖', robot_face: '🤖',
  // ── Cats ──
  smiley_cat: '😺',
  smile_cat: '😸',
  joy_cat: '😹',
  heart_eyes_cat: '😻',
  smirk_cat: '😼',
  kissing_cat: '😽',
  scream_cat: '🙀',
  crying_cat_face: '😿',
  pouting_cat: '😾',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  // ── Hands & body ──
  wave: '👋', wave_hand: '👋',
  raised_back_of_hand: '🤚',
  raised_hand_with_fingers_splayed: '🖐️',
  hand: '✋', raised_hand: '✋',
  vulcan_salute: '🖖',
  ok_hand: '👌',
  pinched_fingers: '🤌',
  pinching_hand: '🤏',
  v: '✌️', victory_hand: '✌️',
  crossed_fingers: '🤞',
  love_you_gesture: '🤟',
  metal: '🤘',
  call_me_hand: '🤙',
  point_left: '👈',
  point_right: '👉',
  point_up_2: '👆',
  middle_finger: '🖕', fu: '🖕',
  point_down: '👇',
  point_up: '☝️',
  '+1': '👍', thumbsup: '👍', thumbup: '👍', thumbs_up: '👍',
  '-1': '👎', thumbsdown: '👎', thumbdown: '👎', thumbs_down: '👎',
  fist_raised: '✊', fist: '✊',
  fist_oncoming: '👊', facepunch: '👊', punch: '👊',
  fist_left: '🤛',
  fist_right: '🤜',
  clap: '👏', clapping_hands: '👏',
  raised_hands: '🙌',
  open_hands: '👐',
  palms_up_together: '🤲',
  handshake: '🤝',
  pray: '🙏', folded_hands: '🙏',
  writing_hand: '✍️',
  nail_care: '💅',
  selfie: '🤳',
  muscle: '💪', flexed_biceps: '💪',
  // ── Hearts & symbols of feeling ──
  heart: '❤️', red_heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  heart_on_fire: '❤️‍🔥',
  two_hearts: '💕',
  revolving_hearts: '💞',
  heartbeat: '💓',
  heartpulse: '💗',
  sparkling_heart: '💖',
  cupid: '💘',
  gift_heart: '💝',
  heart_decoration: '💟',
  heavy_heart_exclamation: '❣️',
  // ── Celebration & misc objects ──
  fire: '🔥', flame: '🔥',
  '100': '💯', hundred: '💯',
  sparkles: '✨',
  star: '⭐',
  star2: '🌟', glowing_star: '🌟',
  dizzy: '💫',
  boom: '💥', collision: '💥',
  anger: '💢',
  sweat_drops: '💦',
  dash: '💨',
  zzz: '💤',
  tada: '🎉', party_popper: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  trophy: '🏆',
  '1st_place_medal': '🥇',
  '2nd_place_medal': '🥈',
  '3rd_place_medal': '🥉',
  medal_sports: '🏅',
  zap: '⚡', lightning: '⚡',
  bulb: '💡', light_bulb: '💡',
  key: '🔑',
  lock: '🔒',
  unlock: '🔓',
  bell: '🔔',
  no_bell: '🔕',
  loudspeaker: '📢',
  mega: '📣', megaphone: '📣',
  speech_balloon: '💬',
  thought_balloon: '💭',
  white_check_mark: '✅',
  heavy_check_mark: '✔️', check_mark: '✔️',
  ballot_box_with_check: '☑️',
  x: '❌', cross_mark: '❌',
  negative_squared_cross_mark: '❎',
  question: '❓',
  grey_question: '❔',
  exclamation: '❗', heavy_exclamation_mark: '❗',
  grey_exclamation: '❕',
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  red_circle: '🔴',
  green_circle: '🟢',
  large_blue_circle: '🔵',
  yellow_circle: '🟡',
  white_circle: '⚪',
  black_circle: '⚫',
  orange_circle: '🟠',
  purple_circle: '🟣',
  brown_circle: '🟤',
  // ── Tech, work, study ──
  rocket: '🚀',
  eyes: '👀',
  eye: '👁️',
  brain: '🧠',
  books: '📚',
  book: '📖', open_book: '📖',
  memo: '📝', pencil: '📝',
  pencil2: '✏️',
  page_facing_up: '📄',
  paperclip: '📎',
  pushpin: '📌',
  round_pushpin: '📍',
  link: '🔗',
  bar_chart: '📊',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  mag: '🔍',
  mag_right: '🔎',
  globe_with_meridians: '🌐',
  earth_africa: '🌍',
  earth_americas: '🌎',
  earth_asia: '🌏',
  alarm_clock: '⏰',
  hourglass_flowing_sand: '⏳',
  hourglass: '⌛',
  microphone: '🎤', mic: '🎤',
  musical_note: '🎵',
  notes: '🎶', musical_notes: '🎶',
  headphones: '🎧',
  camera: '📷',
  camera_flash: '📸',
  clapper: '🎬',
  tv: '📺',
  computer: '💻', laptop: '💻',
  desktop_computer: '🖥️',
  iphone: '📱', mobile_phone: '📱',
  telephone: '☎️',
  wrench: '🔧',
  hammer: '🔨',
  gear: '⚙️',
  nut_and_bolt: '🔩',
  magnet: '🧲',
  test_tube: '🧪',
  microscope: '🔬',
  dart: '🎯', bullseye: '🎯',
  game_die: '🎲',
  jigsaw: '🧩',
  // ── Food & drink ──
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  taco: '🌮',
  sushi: '🍣',
  doughnut: '🍩', donut: '🍩',
  coffee: '☕',
  beer: '🍺',
  wine_glass: '🍷',
  // ── Animals & nature ──
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  fox_face: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  eagle: '🦅',
  duck: '🦆',
  owl: '🦉',
  wolf: '🐺',
  horse: '🐴',
  unicorn: '🦄',
  bee: '🐝', honeybee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  lady_beetle: '🐞',
  snake: '🐍',
  turtle: '🐢',
  octopus: '🐙',
  crab: '🦀',
  tropical_fish: '🐠',
  whale: '🐳',
  shark: '🦈',
  cherry_blossom: '🌸',
  rose: '🌹',
  sunflower: '🌻',
  hibiscus: '🌺',
  tulip: '🌷',
  seedling: '🌱',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  four_leaf_clover: '🍀',
  apple: '🍎',
  green_apple: '🍏',
  pear: '🍐',
  tangerine: '🍊',
  lemon: '🍋',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  blueberries: '🫐',
  peach: '🍑',
  rainbow: '🌈',
  sunny: '☀️', sun: '☀️',
  partly_sunny: '⛅',
  cloud: '☁️',
  snowflake: '❄️',
  ocean: '🌊',
  // ── Arrows & signs ──
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrow_upper_right: '↗️',
  arrow_lower_right: '↘️',
  arrow_lower_left: '↙️',
  arrow_upper_left: '↖️',
  leftwards_arrow_with_hook: '↩️',
  arrow_right_hook: '↪️',
  arrows_counterclockwise: '🔄',
  arrows_clockwise: '🔃',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  heavy_division_sign: '➗',
  heavy_multiplication_x: '✖️',
  infinity: '♾️',
  copyright: '©️',
  registered: '®️',
  tm: '™️',
  recycle: '♻️',
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  white_flag: '🏳️',
  black_flag: '🏴',
  // ── People & wearables ──
  baby: '👶',
  boy: '👦',
  girl: '👧',
  man: '👨',
  woman: '👩',
  older_man: '👴',
  older_woman: '👵',
  crown: '👑',
  gem: '💎',
  graduation_cap: '🎓', mortar_board: '🎓',
};

// `:name:` where name is letters/digits/`_`/`+`/`-`. Global + case-insensitive
// for the replace; the presence check below uses a separate non-global literal
// so there is no shared `lastIndex` to reset.
const SHORTCODE = /:([a-z0-9_+-]{1,40}):/gi;

/** Cheap "is it even worth a pass?" test, so the common case costs one indexOf. */
export function hasShortcode(text: string): boolean {
  return !!text && text.indexOf(':') !== -1 && /:[a-z0-9_+-]{1,40}:/i.test(text);
}

// A shortcode has to stand on its own. Glued to a word character on either
// side it is literal text, and converting it mangles perfectly ordinary
// strings: `1:100:2` would become `1💯2`, and so would the middle of
// `host:fire:port` or a `key:value:` pair. `_` counts as word-ish (it reads as
// an identifier); `+` and `-` do not, so `C++ :fire:` still works.
const WORDISH = /[A-Za-z0-9_]/;

function standsAlone(str: string, start: number, end: number): boolean {
  const before = start > 0 ? str[start - 1] : '';
  const after = end < str.length ? str[end] : '';
  return !WORDISH.test(before) && !WORDISH.test(after);
}

/**
 * Replace every *known* `:shortcode:` with its emoji. Unknown names, colon runs
 * that are not shortcodes at all (`10:30:45`, `16:9`) and known names embedded
 * mid-token are all returned exactly as they came in.
 */
export function replaceShortcodes(text: string): string {
  if (!text || text.indexOf(':') === -1) return text;
  return text.replace(SHORTCODE, (whole, name: string, offset: number, str: string) => {
    const key = name.toLowerCase();
    if (!Object.prototype.hasOwnProperty.call(TABLE, key)) return whole;
    if (!standsAlone(str, offset, offset + whole.length)) return whole;
    return TABLE[key];
  });
}

export const SHORTCODES = TABLE;

// Code is quoted on purpose: a YAML line reading `icon: :fire:` or a snippet
// about shortcodes must survive verbatim. Splitting on fences and inline code
// spans is cheap and keeps the substitution where prose lives.
const CODE = /(^|\n)(?: {0,3})(```|~~~)[^\n]*\n[\s\S]*?(?:\n(?: {0,3})\2[^\n]*(?=\n|$)|$)|`+[^`\n]*`+/g;

/**
 * `replaceShortcodes` applied to prose only — fenced blocks and inline code
 * spans pass through untouched.
 */
export function replaceShortcodesInProse(text: string): string {
  if (!hasShortcode(text)) return text;
  let out = '';
  let last = 0;
  CODE.lastIndex = 0;
  for (let m = CODE.exec(text); m; m = CODE.exec(text)) {
    out += replaceShortcodes(text.slice(last, m.index)) + m[0];
    last = m.index + m[0].length;
  }
  return out + replaceShortcodes(text.slice(last));
}
